In [1]:
%matplotlib inline
import pandas as pd
import MangroveConservation.get_twitter_data as getTwitterdata
import MangroveConservation.clean_text as clean
import MangroveConservation.network_analysis as network
import MangroveConservation.sentiment_analaysis as sentiment

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/gongmimi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
#linting
!pylint get_twitter_data.py

In [3]:
help(getTwitterdata.get_data)

Help on function get_data in module MangroveConservation.get_twitter_data:

get_data(SEARCH_TERM, key, secret, access_token, access_token_secret, start_time, end_time, file_name)
    get twitter data through twitter API from full archive search sand box and return all twitters
    based on
     search term,
     the geographic location of interest
     the time period of interest.
     and personal twitter account information.

     Reference: https://github.com/geduldig/TwitterAPI/tree/master/TwitterAPI
     Reference: https://developer.twitter.com/en/docs/tweets/search/overview

In [17]:
###get twitter data and save it into the directory

#code is not working to combine the search terms, date and csv file
#search_term = '(mangrove ecosystem)OR(mangrove forest)'
#search_location = 'CN'
#SEARCH_TERM = search_term+' lang:en'+' place:'+search_location


SEARCH_TERM='mangrove'
start_time ="201901010000"
end_time="201912310000"
file_name='mangrove.csv'

key = 'i2uWM8Fvt36ipy3pEXk5Cy7ue'
secret = 'FKZBP7QjykINzuAJPVaEsO5l106xd939lmNmXoWQhl0Arqhpzz'
access_token = '2972155805-8lMqqpd1NQR8yXPcMZHEupJLa0UID36VO1ggwVF'
access_token_secret = 'Anw4LVzCi6AxxvZSZVKIwbthEDigUKSCgmuwgCpdPhGk4'


#file_name = 'mangrove_twitters_'+search_location +start_time+end_time+'.csv'
#getTwitterdata.get_data(SEARCH_TERM,key,secret,access_token,access_token_secret,start_time,end_time,file_name)

In [9]:
import pandas as pd
import numpy as np
import re
from datetime import datetime, timezone

In [22]:
tweets = clean.ImportTweet("mangrove1.csv")

ValueError: Length mismatch: Expected axis has 8 elements, new values have 10 elements

In [16]:
#clean the dataset
raw = pd.read_csv('mangrove1.csv',header=None)
raw.columns = ['created_at','follower_count','id','text','user_bio','user_joined','user_location','username']

# convert time format to UTC
time=[]
for i in raw["created_at"]:
    time.append(datetime.strptime(i,'%a %b %d %H:%M:%S %z %Y').replace(tzinfo=timezone.utc).astimezone(tz=None).strftime('%Y-%m-%d %H:%M:%S'))
raw.insert(0, "time",time)
raw["time"] = pd.to_datetime(raw["time"], utc = True)
raw2 = raw.drop(columns="created_at")
# clean text
cleantweet=[]
for i in raw2["text"]:
    cleantweet.append(TweetCleaner(i))
raw2.insert(3, "tweet", cleantweet)
df = raw3.drop(columns="text")

NameError: name 'TweetCleaner' is not defined

,Mon Dec 30 23:47:50 +0000 2019,SoniaRo59106523,"Puerto Rico, USA",210,364,False,Unnamed: 6,0,0.1,b'RT @seavoicenews: Easily one of the craziest story of the year!\n\nhttps://t.co/RDqcvuiAYx'
0,Mon Dec 30 21:11:32 +0000 2019,nach212,"Los Angeles, CA",379,268,False,NaN,0,6,"b""I might regret this in more than one way... ..."
1,Mon Dec 30 20:11:45 +0000 2019,chmnaidu,Hyderabad Telangana India ð®ð³,19465,18122,False,NaN,0,0,"b'India State of Forest Report, #ISFR2019 : \n..."
2,Mon Dec 30 19:30:33 +0000 2019,ShredderShrey,"New Delhi, India",43,102,False,NaN,0,0,b'RT @airnewsalerts: India State of Forest Rep...
3,Mon Dec 30 18:01:01 +0000 2019,ShwetalPShah,India,335,1114,False,NaN,2,3,b'Government of India released Forest report 2...
4,Mon Dec 30 17:40:59 +0000 2019,vinayfeels,"à¤ªà¤¶à¥à¤à¤¿à¤® à¤¬à¤à¤à¤¾à¤², à¤­à¤¾à¤°à¤¤",0,0,False,NaN,0,0,"b""'JOURNEY ABOUT TO START FOR THE MANGROVE FOR..."
...,...,...,...,...,...,...,...,...,...,...
204,Mon Dec 30 17:40:59 +0000 2019,vinayfeels,"à¤ªà¤¶à¥à¤à¤¿à¤® à¤¬à¤à¤à¤¾à¤², à¤­à¤¾à¤°à¤¤",0,0,False,NaN,0,0,'JOURNEY ABOUT TO START FOR THE MANGROVE FORES...
205,Mon Dec 30 17:37:34 +0000 2019,ViralVaishnav2,New Delhi,554,4990,False,NaN,0,0,RT @airnewsalerts: India State of Forest Repor...
206,Mon Dec 30 17:24:12 +0000 2019,vinayfeels,"à¤ªà¤¶à¥à¤à¤¿à¤® à¤¬à¤à¤à¤¾à¤², à¤­à¤¾à¤°à¤¤",0,0,False,NaN,0,0,"'ABOUT TO ENTER BICHITRAPUR MANGROVE FOREST,OD..."
207,Mon Dec 30 17:14:07 +0000 2019,MALVIYAMalviya9,NaN,69,320,False,NaN,0,0,RT @PIBBhubaneswar: The Mangrove ecosystems ar...
208,Mon Dec 30 17:09:38 +0000 2019,SubirBhowmik,"Kolkata, India",418,102,False,NaN,0,0,RT @Bangladesh_BN: Noting that #Sundarbans hel...